### ISSUE TITLE
ROS Buildfarm failure for kinetic package.

### ISSUE THREAD

**Issue by zmk5** [ACSLab/pheeno_ros_sim#5]
```
------------------------------------------
[...truncated 577.42 KB...]
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:115:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<GpsSensor> GpsSensorPtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:119:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<Noise> NoisePtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:123:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<GaussianNoiseModel> GaussianNoiseModelPtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:126:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<ImageGaussianNoiseModel>
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:131:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<WirelessTransceiver> WirelessTransceiverPtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:135:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<WirelessTransmitter> WirelessTransmitterPtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:139:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<WirelessReceiver> WirelessReceiverPtr;
                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:147:25: error: ‘SensorPtr’ was not declared in this scope
    typedef std::vector<SensorPtr> Sensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:147:25: note: suggested alternative:
In file included from /usr/include/gazebo-7/gazebo/msgs/joint.pb.h:30:0,
                from /usr/include/gazebo-7/gazebo/msgs/MessageTypes.hh:43,
                from /usr/include/gazebo-7/gazebo/msgs/msgs.hh:30,
                from /usr/include/gazebo-7/gazebo/physics/World.hh:39,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:5:
/usr/include/gazebo-7/gazebo/msgs/sensor.pb.h:924:49: note:   ‘gazebo::msgs::SensorPtr’
typedef boost::shared_ptr<gazebo::msgs::Sensor> SensorPtr;
                                                ^
In file included from /usr/include/gazebo-7/gazebo/sensors/Sensor.hh:30:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:147:34: error: template argument 1 is invalid
    typedef std::vector<SensorPtr> Sensor_V;
                                 ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:147:34: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:151:25: error: ‘RaySensorPtr’ was not declared in this scope
    typedef std::vector<RaySensorPtr> RaySensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:151:25: note: suggested alternative:
In file included from /usr/include/gazebo-7/gazebo/msgs/sensor.pb.h:29:0,
                from /usr/include/gazebo-7/gazebo/msgs/joint.pb.h:30,
                from /usr/include/gazebo-7/gazebo/msgs/MessageTypes.hh:43,
                from /usr/include/gazebo-7/gazebo/msgs/msgs.hh:30,
                from /usr/include/gazebo-7/gazebo/physics/World.hh:39,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:5:
/usr/include/gazebo-7/gazebo/msgs/raysensor.pb.h:528:52: note:   ‘gazebo::msgs::RaySensorPtr’
typedef boost::shared_ptr<gazebo::msgs::RaySensor> RaySensorPtr;
                                                   ^
In file included from /usr/include/gazebo-7/gazebo/sensors/Sensor.hh:30:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:151:37: error: template argument 1 is invalid
    typedef std::vector<RaySensorPtr> RaySensor_V;
                                    ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:151:37: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:155:25: error: ‘CameraSensorPtr’ was not declared in this scope
    typedef std::vector<CameraSensorPtr> CameraSensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:155:25: note: suggested alternative:
In file included from /usr/include/gazebo-7/gazebo/msgs/MessageTypes.hh:11:0,
                from /usr/include/gazebo-7/gazebo/msgs/msgs.hh:30,
                from /usr/include/gazebo-7/gazebo/physics/World.hh:39,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:5:
/usr/include/gazebo-7/gazebo/msgs/camerasensor.pb.h:546:55: note:   ‘gazebo::msgs::CameraSensorPtr’
typedef boost::shared_ptr<gazebo::msgs::CameraSensor> CameraSensorPtr;
                                                      ^
In file included from /usr/include/gazebo-7/gazebo/sensors/Sensor.hh:30:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:155:40: error: template argument 1 is invalid
    typedef std::vector<CameraSensorPtr> CameraSensor_V;
                                       ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:155:40: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:159:25: error: ‘MultiCameraSensorPtr’ was not declared in this scope
    typedef std::vector<MultiCameraSensorPtr> MultiCameraSensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:159:45: error: template argument 1 is invalid
    typedef std::vector<MultiCameraSensorPtr> MultiCameraSensor_V;
                                            ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:159:45: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:163:25: error: ‘DepthCameraSensorPtr’ was not declared in this scope
    typedef std::vector<DepthCameraSensorPtr> DepthCameraSensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:163:45: error: template argument 1 is invalid
    typedef std::vector<DepthCameraSensorPtr> DepthCameraSensor_V;
                                            ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:163:45: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:167:25: error: ‘ContactSensorPtr’ was not declared in this scope
    typedef std::vector<ContactSensorPtr> ContactSensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:167:25: note: suggested alternative:
In file included from /usr/include/gazebo-7/gazebo/msgs/MessageTypes.hh:19:0,
                from /usr/include/gazebo-7/gazebo/msgs/msgs.hh:30,
                from /usr/include/gazebo-7/gazebo/physics/World.hh:39,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:5:
/usr/include/gazebo-7/gazebo/msgs/contactsensor.pb.h:211:56: note:   ‘gazebo::msgs::ContactSensorPtr’
typedef boost::shared_ptr<gazebo::msgs::ContactSensor> ContactSensorPtr;
                                                       ^
In file included from /usr/include/gazebo-7/gazebo/sensors/Sensor.hh:30:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:167:41: error: template argument 1 is invalid
    typedef std::vector<ContactSensorPtr> ContactSensor_V;
                                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:167:41: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:171:25: error: ‘ImuSensorPtr’ was not declared in this scope
    typedef std::vector<ImuSensorPtr> ImuSensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:171:37: error: template argument 1 is invalid
    typedef std::vector<ImuSensorPtr> ImuSensor_V;
                                    ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:171:37: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:175:25: error: ‘GpuRaySensorPtr’ was not declared in this scope
    typedef std::vector<GpuRaySensorPtr> GpuRaySensor_V;
                        ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:175:40: error: template argument 1 is invalid
    typedef std::vector<GpuRaySensorPtr> GpuRaySensor_V;
                                       ^
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:175:40: error: template argument 2 is invalid
/usr/include/gazebo-7/gazebo/sensors/SensorTypes.hh:199:18: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
    typedef std::shared_ptr<LogicalCameraSensor> LogicalCameraSensorPtr;
                 ^
In file included from /usr/include/gazebo-7/gazebo/sensors/Sensor.hh:33:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:
/usr/include/gazebo-7/gazebo/common/Events.hh:346:35: error: ‘ElementPtr’ is not a member of ‘sdf’
      public: static EventT<void (sdf::ElementPtr,
                                  ^
/usr/include/gazebo-7/gazebo/common/Events.hh:349:33: error: expression list treated as compound expression in functional cast [-fpermissive]
                  const uint32_t)> createSensor;
                                ^
/usr/include/gazebo-7/gazebo/common/Events.hh:349:34: error: template argument 1 is invalid
                  const uint32_t)> createSensor;
                                 ^
/usr/include/gazebo-7/gazebo/common/Events.hh: In static member function ‘static gazebo::event::ConnectionPtr gazebo::event::Events::ConnectCreateSensor(T)’:
/usr/include/gazebo-7/gazebo/common/Events.hh:203:37: error: request for member ‘Connect’ in ‘gazebo::event::Events::createSensor’, which is of non-class type ‘int’
              { return createSensor.Connect(_subscriber); }
                                    ^
/usr/include/gazebo-7/gazebo/common/Events.hh: In static member function ‘static void gazebo::event::Events::DisconnectCreateSensor(gazebo::event::ConnectionPtr)’:
/usr/include/gazebo-7/gazebo/common/Events.hh:208:30: error: request for member ‘Disconnect’ in ‘gazebo::event::Events::createSensor’, which is of non-class type ‘int’
              { createSensor.Disconnect(_subscriber); }
                             ^
In file included from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:7:0:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh: At global scope:
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:50:70: error: expected template-name before ‘<’ token
    class GAZEBO_VISIBLE Sensor : public std::enable_shared_from_this<Sensor>
                                                                     ^
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:50:70: error: expected ‘{’ before ‘<’ token
/usr/include/gazebo-7/gazebo/sensors/Sensor.hh:50:70: error: expected unqualified-id before ‘<’ token
In file included from /usr/include/boost/asio/handler_type.hpp:20:0,
                from /usr/include/boost/asio/async_result.hpp:19,
                from /usr/include/boost/asio.hpp:20,
                from /usr/include/gazebo-7/gazebo/transport/Connection.hh:23,
                from /usr/include/gazebo-7/gazebo/transport/transport.hh:3,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:11:
/usr/include/boost/asio/detail/push_options.hpp:71:40: error: expected ‘}’ before end of line
/usr/include/boost/asio/detail/push_options.hpp:71:40: error: expected ‘}’ before end of line
/usr/include/boost/asio/detail/push_options.hpp:71:40: error: expected declaration before end of line
In file included from /usr/include/gazebo-7/gazebo/physics/World.hh:43:0,
                from /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/src/gazebo_ros_ir_sensor.cpp:5:
/usr/include/gazebo-7/gazebo/common/Event.hh: In instantiation of ‘void gazebo::event::EventT<T>::Disconnect(int) [with T = void(bool)]’:
/usr/include/gazebo-7/gazebo/common/Event.hh:638:7:   required from ‘void gazebo::event::EventT<T>::Disconnect(gazebo::event::ConnectionPtr) [with T = void(bool); gazebo::event::ConnectionPtr = boost::shared_ptr<gazebo::event::Connection>]’
/usr/include/gazebo-7/gazebo/common/Events.hh:50:45:   required from here
/usr/include/gazebo-7/gazebo/common/Event.hh:657:61: error: ‘class gazebo::event::EventTPrivate<void(bool)>’ has no member named ‘connections’
      auto const &it = this->myDataPtr->connections.find(_id);
                                                            ^
/usr/include/gazebo-7/gazebo/common/Event.hh:659:14: error: ‘class gazebo::event::EventTPrivate<void(bool)>’ has no member named ‘connections’
      if (it != this->myDataPtr->connections.end())
             ^
/usr/include/gazebo-7/gazebo/common/Event.hh:662:9: error: request for member ‘push_back’ in ‘((gazebo::event::EventT<void(bool)>*)this)->gazebo::event::EventT<void(bool)>::myDataPtr->gazebo::event::EventTPrivate<void(bool)>::connectionsToRemove’, which is of non-class type ‘int’
        this->myDataPtr->connectionsToRemove.push_back(it);
        ^
/usr/include/gazebo-7/gazebo/common/Event.hh: In instantiation of ‘void gazebo::event::EventT<T>::Disconnect(int) [with T = void()]’:
/usr/include/gazebo-7/gazebo/common/Event.hh:638:7:   required from ‘void gazebo::event::EventT<T>::Disconnect(gazebo::event::ConnectionPtr) [with T = void(); gazebo::event::ConnectionPtr = boost::shared_ptr<gazebo::event::Connection>]’
/usr/include/gazebo-7/gazebo/common/Events.hh:62:44:   required from here
/usr/include/gazebo-7/gazebo/common/Event.hh:657:61: error: ‘class gazebo::event::EventTPrivate<void()>’ has no member named ‘connections’
      auto const &it = this->myDataPtr->connections.find(_id);
                                                            ^
/usr/include/gazebo-7/gazebo/common/Event.hh:659:14: error: ‘class gazebo::event::EventTPrivate<void()>’ has no member named ‘connections’
      if (it != this->myDataPtr->connections.end())
             ^
/usr/include/gazebo-7/gazebo/common/Event.hh:662:9: error: request for member ‘push_back’ in ‘((gazebo::event::EventT<void()>*)this)->gazebo::event::EventT<void()>::myDataPtr->gazebo::event::EventTPrivate<void()>::connectionsToRemove’, which is of non-class type ‘int’
        this->myDataPtr->connectionsToRemove.push_back(it);
        ^
/usr/include/gazebo-7/gazebo/common/Event.hh: In instantiation of ‘void gazebo::event::EventT<T>::Disconnect(int) [with T = void(std::__cxx11::basic_string<char>)]’:
/usr/include/gazebo-7/gazebo/common/Event.hh:638:7:   required from ‘void gazebo::event::EventT<T>::Disconnect(gazebo::event::ConnectionPtr) [with T = void(std::__cxx11::basic_string<char>); gazebo::event::ConnectionPtr = boost::shared_ptr<gazebo::event::Connection>]’
/usr/include/gazebo-7/gazebo/common/Events.hh:85:52:   required from here
/usr/include/gazebo-7/gazebo/common/Event.hh:657:61: error: ‘class gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>)>’ has no member named ‘connections’
      auto const &it = this->myDataPtr->connections.find(_id);
                                                            ^
/usr/include/gazebo-7/gazebo/common/Event.hh:659:14: error: ‘class gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>)>’ has no member named ‘connections’
      if (it != this->myDataPtr->connections.end())
             ^
/usr/include/gazebo-7/gazebo/common/Event.hh:662:9: error: request for member ‘push_back’ in ‘((gazebo::event::EventT<void(std::__cxx11::basic_string<char>)>*)this)->gazebo::event::EventT<void(std::__cxx11::basic_string<char>)>::myDataPtr->gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>)>::connectionsToRemove’, which is of non-class type ‘int’
        this->myDataPtr->connectionsToRemove.push_back(it);
        ^
/usr/include/gazebo-7/gazebo/common/Event.hh: In instantiation of ‘void gazebo::event::EventT<T>::Disconnect(int) [with T = void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)]’:
/usr/include/gazebo-7/gazebo/common/Event.hh:638:7:   required from ‘void gazebo::event::EventT<T>::Disconnect(gazebo::event::ConnectionPtr) [with T = void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>); gazebo::event::ConnectionPtr = boost::shared_ptr<gazebo::event::Connection>]’
/usr/include/gazebo-7/gazebo/common/Events.hh:109:57:   required from here
/usr/include/gazebo-7/gazebo/common/Event.hh:657:61: error: ‘class gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)>’ has no member named ‘connections’
      auto const &it = this->myDataPtr->connections.find(_id);
                                                            ^
/usr/include/gazebo-7/gazebo/common/Event.hh:659:14: error: ‘class gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)>’ has no member named ‘connections’
      if (it != this->myDataPtr->connections.end())
             ^
/usr/include/gazebo-7/gazebo/common/Event.hh:662:9: error: request for member ‘push_back’ in ‘((gazebo::event::EventT<void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)>*)this)->gazebo::event::EventT<void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)>::myDataPtr->gazebo::event::EventTPrivate<void(std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>)>::connectionsToRemove’, which is of non-class type ‘int’
        this->myDataPtr->connectionsToRemove.push_back(it);
        ^
CMakeFiles/gazebo_ros_ir_sensor.dir/build.make:65: recipe for target 'CMakeFiles/gazebo_ros_ir_sensor.dir/src/gazebo_ros_ir_sensor.cpp.o' failed
make[4]: *** [CMakeFiles/gazebo_ros_ir_sensor.dir/src/gazebo_ros_ir_sensor.cpp.o] Error 1
make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/obj-arm-linux-gnueabihf'
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/gazebo_ros_ir_sensor.dir/all' failed
make[3]: *** [CMakeFiles/gazebo_ros_ir_sensor.dir/all] Error 2
make[3]: Leaving directory '/tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/obj-arm-linux-gnueabihf'
Makefile:130: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4/obj-arm-linux-gnueabihf'
dh_auto_build: make -j1 returned exit code 2
	cd /tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4
debian/rules:36: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/tmp/binarydeb/ros-kinetic-pheeno-ros-sim-0.1.4'
debian/rules:23: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Building failed
Traceback (most recent call last):
 File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
   subprocess.check_call(cmd, cwd=source_dir)
 File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-kinetic-pheeno-ros-sim']' returned non-zero exit status 1
# END SUBSECTION

--------------------------------------------------------------------------------------------------
`apt-src build ros-kinetic-pheeno-ros-sim` failed.
This is usually because of an error building the package.
The traceback from this failure (just above) is printed for completeness, but you can ignore it.
You should look above `E: Building failed` in the build log for the actual cause of the failure.
--------------------------------------------------------------------------------------------------

Build step 'Execute shell' marked build as failure
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 13707 killed;
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

I believe this is a problem with having it trying to build with C++11.

**Comment by stoneeve415** [comment]
Hi！ Did you solve the problem?
I also got the same error when i catkin_make! 
can you help me？Thanks～ @zmk5

**Comment by zmk5** [comment]
@stoneeve415 Are you having issues with the buildfarm or with just `catkin_make`?

If it is just running `catkin_make`, add the following line to your `CMakeLists.txt` file after the `project()` section:

`
add_compile_options(-std=c++11)
`

**Comment by zmk5** [comment]
To anyone that had problems using the buildfarm with C++ 11 code, when writing the `CMakeLists.txt` file, use:

`add_compile_options(-std=c++11)`

and **NOT**

`add_definitions(-std=c++11)`
